POST http://localhost:5000/profile
content-type: application/json

{
      "email": "biswassagar927@gmail.com",
      "name": { "FName": "FName", "LName": "LName" },
      "mobile": 89,
      "gender": "Male",
      "DOB": "2002/09/09",
      "address": {
          "street": "street",
          "city": "city",
          "state": "state",
          "pin": 73673
      }
  }